# Generated by Django 3.2.9 on 2021-11-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=240)),
                ('price', models.FloatField()),
                ('priceId', models.CharField(max_length=100)),
                ('mainImage', models.CharField(default='image_url', max_length=200)),
                ('subImage1', models.CharField(default='image_url', max_length=200)),
                ('subImage2', models.CharField(default='image_url', max_length=200)),
                ('region', models.CharField(choices=[('UK', 'THE UNITED KINGDOM'), ('EU', 'EUROPE'), ('USA', 'USA'), ('AUS', 'AUS'), ('ASIA', 'ASIA')], default='UK', max_length=5)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EURO', 'Euro'), ('GBP', 'Great Britain Pound'), ('BAT', 'Basic Attention Token')], default='UK', max_length=5)),
                ('style', models.CharField(choices=[('Sweet', 'Sweet'), ('Bitter', 'Bitter'), ('Sour', 'Sour'), ('Moon', 'Moon')], default='Sweet', max_length=10)),
                ('theme', models.CharField(choices=[('One to watch', 'One to watch'), ('Summer hits', 'Summer hits'), ('Yorkshire', 'Yorkshire'), ('Belgium', 'Belgium')], default='One to watch"', max_length=30)),
                ('releaseDate', models.DateField()),
            ],
        ),
    ]
